Repository MikeAntonio/devops-aula07, pull requests merged in 2018-03, with the labels that each got.

#3 requisito efetuado
  docs/requisitos.md
Labels: análise

#5 V1.0 arquitetura
  docs/arquitetura.md
Labels: arquitetura

#7 Create jogodavelha.py
  src/jogodavelha.py
Labels: programação

#12 Create arquitetura.md
  docs/arquitetura.md
Labels: arquitetura

#13 V1.1-programacao
  src/tabuleiro.py
Labels: programação

#14 V1.1 analise
  docs/requisito.md1
  docs/requit.m1
Labels: análise
